POST https://prod-33.westeurope.logic.azure.com:443/workflows/100eb921ac764d26ab0f76ea52c8cce6/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=EJhgL-wBnJJywgo-rMDstlnDQ_Mm86ExG7rAj0TamjM HTTP/1.1
Content-Type: application/json

{
    "productId": "75542e38-563f-436f-adeb-f426f1dabb5c"
}

###

GET https://serverlessohproduct.trafficmanager.net/api/GetProduct?productId=4c25613a-a3c2-4ef3-8e02-9c335eb23204


###

POST http://localhost:7071/api/create_rating
Content-Type: application/json

{
  "userId": "cc20a6fb-a91f-4192-874d-132493685376",
  "productId": "4c25613a-a3c2-4ef3-8e02-9c335eb23204",
  "locationName": "Sample ice cream shop",
  "rating": 5,
  "userNotes": "I love the subtle notes of orange in this ice cream!"
}

###

GET http://localhost:7071/api/rating/4c25613a-a3c2-4ef3-8e02-9c335eb23204/c8cf74d8-80fa-44e0-b55f-7b9496d230dd

###

GET http://localhost:7071/api/user/cc20a6fb-a91f-4192-874d-132493685376 

###

https://serverlessohproduct.trafficmanager.net/api/GetProducts 

###

https://serverlessohproduct.trafficmanager.net/api/GetProduct?productId=4c25613a-a3c2-4ef3-8e02-9c335eb23204

###
https://serverlessohuser.trafficmanager.net/api/GetUser?userId=cc20a6fb-a91f-4192-874d-132493685376 

###

https://serverlessohproduct.trafficmanager.net/api/GetUser?userId=cc20a6fb-a91f-4192-874d-132493685376

###

POST https://serverlessohmanagementapi.trafficmanager.net/api/team/registerStorageAccount 
Content-Type: application/json

{
  "storageAccountConnectionString": "",
  "teamTableNumber": "london-table-18",
  "blobContainerName": "orders"
}

###

POST https://serverlessohmanagementapi.trafficmanager.net/api/order/combineOrderContent
Content-Type: application/json

{
  "orderHeaderDetailsCSVUrl": "https://meotestorders.blob.core.windows.net/orders/20201015133000-OrderHeaderDetails.csv",
  "orderLineItemsCSVUrl": "https://meotestorders.blob.core.windows.net/orders/20201015133000-OrderLineItems.csv",
  "productInformationCSVUrl": "https://meotestorders.blob.core.windows.net/orders/20201015133000-ProductInformation.csv"
}

###

POST https://serverlessohmanagementapi.trafficmanager.net/api/order/combineOrderContent
Content-Type: application/json

{
  "orderHeaderDetailsCSVUrl": "https://challenge6.blob.core.windows.net/orders/20201019111000-OrderHeaderDetails.csv",
  "orderLineItemsCSVUrl": "https://challenge6.blob.core.windows.net/orders/20201019111000-OrderLineItems.csv",
  "productInformationCSVUrl": "https://challenge6.blob.core.windows.net/orders/20201019111000-ProductInformation.csv"
}

###

POST https://serverlessohmanagementapi.trafficmanager.net/api/team/registerEventHub
Content-Type: application/json

{
  "teamTableNumber": "london-table-18",
  "eventHubConnectionString": "",
  "eventHubName": "pos"
}