name: Build and deploy

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ .github/** ]    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        #pylint `ls -R|grep .py$|xargs`
        pylint `find . -path ./.venv -prune -false -o -iname '*.py'|xargs`

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure Functions Action
        uses: Azure/functions-action@v1.1.5
        with:
          # Name of the Azure Function App
          app-name: meoserverlessopenhack
          # Path to package or folder. *.zip or a folder to deploy
          package: .
          # Function app slot to be deploy to
          # slot-name: # optional
          # Publish profile (*.publishsettings) file contents with web deploy secrets
          publish-profile: ${{ secrets.FUNCTION_APP_PUBLISH_PROFILE }}
